{
  "sksl": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 res;\nuniform float t;\n\nvec4 fragColor;\n\nvec3 FLT_flutter_local_hsl2rgb(vec3 c)\n{\n    vec3 rgb = clamp(abs(mod(vec3(c.x * 6.0) + vec3(0.0, 4.0, 2.0), vec3(6.0)) - vec3(3.0)) - vec3(1.0), vec3(0.0), vec3(1.0));\n    return vec3(c.z) + (((rgb - vec3(0.5)) * c.y) * (1.0 - abs((2.0 * c.z) - 1.0)));\n}\n\nvoid FLT_main()\n{\n    float scale = pow(2.0, mod(t, 15.0)) - 0.5;\n    vec2 rel = flutter_FragCoord.xy / res;\n    rel -= vec2(0.5);\n    rel /= vec2(scale);\n    rel += vec2(0.5);\n    vec2 center = vec2(-0.5, 0.0);\n    vec2 offset = vec2(-0.761573970317840576171875, -0.084759600460529327392578125) - center;\n    float re = ((-2.0) + (3.0 * rel.x)) + offset.x;\n    float im = ((-1.5) + (3.0 * rel.y)) + offset.y;\n    float n = 0.0;\n    float zre = re;\n    float zim = im;\n    for (float tn = 1.0; tn <= 700.0; tn += 1.0)\n    {\n        float tzre = ((zre * zre) - (zim * zim)) + re;\n        zim = ((2.0 * zre) * zim) + im;\n        zre = tzre;\n        n = tn;\n        if ((abs(zre) + abs(zim)) > 16.0)\n        {\n            break;\n        }\n    }\n    if (n == 700.0)\n    {\n        fragColor = vec4(0.0, 0.0, 0.0, 1.0);\n    }\n    else\n    {\n        vec3 hsl = vec3(n / 100.0, 0.89999997615814208984375, 0.60000002384185791015625);\n        vec3 param = hsl;\n        vec3 rgb_1 = FLT_flutter_local_hsl2rgb(param);\n        fragColor = vec4(rgb_1, 1.0);\n    }\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
  "stage": 1,
  "target_platform": 2,
  "uniforms": [
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 0,
      "name": "res",
      "rows": 2,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 1,
      "name": "t",
      "rows": 1,
      "type": 10
    }
  ]
}